### PR TITLE
Monoid Semantics

### PR DESCRIPTION
**Pull request by dangabhi**

### CODE REVIEW

**Comment by dangabhi** [comment]
Ah, my TODOs got through too; should I take the pains to remove them?/

**Comment by piyush-kurur** [comment]
The builds at least for 8.9.1 seems to be failing. Can you check what is the problem

**Comment by piyush-kurur** [comment]
I plan to setup a dune based build as well because that seems to be the future of the build. Unfortunately, we will have to keep the
current _CoqProject /Makefile based one as well for interactive usage.

**Comment by dangabhi** [comment]
> The builds at least for 8.9.1 seems to be failing. Can you check what is the problem

I checked with 8.10.2 (that is the build I readily have available) and the issue is that I had started using the newer `[ ]` allowance to declare implicit but not maximally inserted arguments within `Definition`s. Do you want me to roll this back?

The old way (only using `{ }`) did not afford a way to define an argument implicit but not maximally inserted except by using `Arguments`.

**Comment by piyush-kurur** [comment]
On Fri, Oct 16, 2020 at 11:11:32PM -0700, dangabhi wrote:
> > The builds at least for 8.9.1 seems to be failing. Can you check what is the problem
> 
> I checked with 8.10.2 (that is the build I readily have available)
> and the issue is that I had started using the newer `[ ]` allowance
> to declare implicit but not maximally inserted arguments within
> `Definition`s. Do you want me to roll this back?

No, I think we can afford to move to the new version of coq.

> 
> The old way (only using `{ }`) did not afford a way to define an
> argument implicit but not maximally inserted except by using
> `Arguments`.

Instead can you disable the CI build against 8.9. Look into
the .github/workflows/ci.yml file

Regards,

ppk

**Comment by dangabhi** [comment]
The new binder notation `[ ]` has been introduced only in Coq 8.12. The current checks are with 8.9.1, 8.10.2 and 8.11.0.

I am guessing this is going to change your opinion on the rollback :)

**Comment by piyush-kurur** [comment]
On Sat, Oct 17, 2020 at 12:30:27AM -0700, dangabhi wrote:
> The new binder notation `[ ]` has been introduced only in Coq 8.12. The current checks are with 8.9.1, 8.10.2 and 8.11.0.
> 
> I am guessing this is going to change your opinion on the rollback :)

Yes this definitely changes everything. Okey you have to do the rewrite then ;)

**Comment by dangabhi** [comment]
This time I seem to have run into something that is breaking only on 8.9.1. Want me to figure it out? Or just cull 8.9.1?

**Comment by piyush-kurur** [comment]
Can you get this pull request in shape so that I can merge this ?
Also please rebase it with the current master where there is a dune based build setup.

**Comment by piyush-kurur** [comment]
Can you just disable the 8.9 build and resend the pull request ? That way I will know whether it will build with other versions.

**Comment by dangabhi** [comment]
Have pushed the change onto my branch. Not quite sure why it is not showing up here yet.

**Comment by piyush-kurur** [comment]
You also need to update the dune file now remember. In this particular case have a look at the src/dune file.

**Comment by dangabhi** [comment]
The 8.10.2 build (make on the correct opam switch) does succeed on my machine. Not quite sure what the issue with that build here is! Ideas?

**Comment by piyush-kurur** [comment]
There is now two builds. The make based and the dune based. I think you have not updated the dune build files.

**Pull request merged**
