### PR TITLE
Restricted Annotations

### PR DESCRIPTION
**Pull request by dangabhi**
Comment on what you want polished @piyush-kurur and this can be merged post.

### CODE REVIEW

**Comment by piyush-kurur** [comment]
Some things are failing

**Comment by dangabhi** [comment]
I can compile this locally for 8.10.2, 8.11.0 and 8.13.2. Suggestions?

**Comment by piyush-kurur** [comment]
Did you forget to commit Verse/AnnotateCode.v

**Comment by dangabhi** [comment]
No that is not the problem. fb13145 takes care of that.

**Comment by piyush-kurur** [comment]
Okey I see why it is failing. There are two builds, one based on dune and the other based on the old Makefile. It is the dune build that is failing. Update the dune file in the appropriate directory

**Comment by dangabhi** [comment]
My bad! Thanks.

**Comment by dangabhi** [comment]
Accidental pushes removed. Rolled back to the original pull request.

**Comment by piyush-kurur** [comment]
Can you rebase it to current master. I have added some additional stuff since you sent this pull request.

**Pull request merged**
